server:
  http:
    addr: 0.0.0.0:8011
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9011
    timeout: 1s
  repo_path: /Users/zhouyang/learn/warehouse/repo
data:
  database:
    driver: mysql
    # source: root:root@tcp(127.0.0.1:3306)/test
    source: root:123456@tcp(127.0.0.1:3306)/warehouse?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
